medias_dict = {
    'chile': [
        # Arica y Parinacota
        'https://www.elmorrocotudo.cl/',
        'https://www.aricaldia.cl/',
        'https://www.aricahoy.cl/',
        'https://www.aricamia.cl/',
        'https://www.chasquis.cl/diario/',
        # Tarapacá
        'https://elsoldeiquique.cl/',
        'https://www.elboyaldia.cl/',
        'https://elreporterodeiquique.com/',
        'https://lakalle.cl/',
        # Antogafasta
        'https://www.diarioantofagasta.cl/',
        'https://www.elnortero.cl/',
        'https://www.antofagastanoticias.cl/',
        'https://elamerica.cl/',
        'https://enlalinea.cl/home/',
        # Atacama
        'https://www.atacamanoticias.cl/',
        'https://tierramarillano.cl/',
        'https://www.chanarcillo.cl/',
        'https://www.elquehaydecierto.cl/',
        'https://www.atacamaenlinea.cl/',
        # Coquimbo
        'https://www.diarioeldia.cl/',
        'https://www.laperladellimari.cl/',
        'https://laserenaonline.cl/',
        'https://www.elserenense.cl/',
        'http://www.elovallino.cl/',
        'https://ovallehoy.cl/',
        'https://www.elcoquimbano.cl/',
        # Valparaiso
        'https://www.epicentrochile.com/',
        'https://diariolaquinta.cl/',
        'https://www.elmartutino.cl/',
        'https://laregionhoy.cl/',
        'https://www.observador.cl/',
        'https://eltrabajo.cl/portal/',
        'https://www.elaconcagua.cl/',
        'https://www.aconcaguadigital.cl/',
        'https://elproa.cl/',
        'http://www.elandino.cl/',
        'http://www.losandesonline.cl/',
        'https://www.elinformador.cl/',
        # Santiago
        'https://www.adnradio.cl/',
        'https://www.elmostrador.cl/',
        'https://www.laizquierdadiario.cl/Chile',
        'https://www.lanacion.cl/',
        'https://www.biobiochile.cl/',
        'https://www.emol.com',
        'https://www.diarioestrategia.cl/',
        'https://www.eldinamo.cl/',
        'https://www.elperiscopio.cl/',
        'https://www.gamba.cl/',
        'https://interferencia.cl/',
        'https://www.latercera.com/canal/pulso/',
        'https://www.tusnoticias.cl/',
        'https://www.centralweb.cl/',
        'https://www.larazon.cl/',
        'https://www.meganoticias.cl/',
        'https://www.elobservatodo.cl/',
        'https://www.elperiodista.cl/',
        'https://elsiglo.cl/',
        'https://elcomunicador.cl/',
        'https://www.theclinic.cl/',
        'https://forbes.cl/',
        'https://cooperativa.cl/',
        'https://www.radioagricultura.cl/',
        'https://www.24horas.cl/',
        'https://www.ciperchile.cl/',
        'https://prensaopal.cl/',
        'https://puranoticia.pnt.cl/',
        'https://radio.ucentral.cl/',
        'https://www.soychile.cl/',
        'https://redgol.cl/',
        'https://verdadahora.cl/',
        # Ohiggins
        'https://www.diarioviregion.cl/',
        'https://www.elrancaguino.cl/',
        'http://www.latribunadecolchagua.cl/',
        'https://www.pagina7.cl/',
        'https://elcachapoal.cl/',
        # Maule
        'https://diariocauquenes.cl/',
        'https://diariocurico.cl/',
        'https://www.elamaule.cl/',
        'https://www.linaresenlinea.cl/',
        'https://www.redmaule.com/',
        # Ñuble
        'https://elsancarlino.cl/',
        'https://www.ladiscusion.cl/',
        'https://araucaniadiario.cl/',
        # Bío-Bío
        'https://www.diarioconcepcion.cl/',
        'https://www.elconcecuente.cl/',
        'https://www.latribuna.cl/',
        'https://elcontraste.cl/',
        'https://www.angelino.cl/',
        'https://resumen.cl/',
        'https://sabes.cl/',
        'https://www.pagina7.cl/',
         # Araucanía
        'https://araucaniadiario.cl/',
        'https://www.clave9.cl/',
        'https://araucanianoticias.cl/',
        'https://www.laopinon.cl/',
        'https://temucodiario.cl/',
        'http://www.primeranota.cl/web/',
        'https://www.prensaciudadana.cl/',
        'https://www.angolinos.cl/',
        'https://www.malleco7.cl/',
        'https://correodellago.cl/',
        'https://www.noticiasdellago.cl/',
        'https://lasnoticiasdemalleco.cl/',
         # Los Ríos
        'https://www.diariodevaldivia.cl/',
        'https://www.diariolaunion.cl/',
        'https://diarioelranco.cl/',
        'https://www.diarioriobueno.cl/',
        'https://www.lavozdepaillaco.cl/',
        'https://www.rioenlinea.cl/',
        'https://www.elnaveghable.cl/',
        'https://periodicolosrios.cl/',
        'https://www.losriosaldia.cl/',
        'https://www.noticiaslosrios.cl/',
        'https://diarioelranco.cl/',
        'https://www.lavozdepaillaco.cl/',
        'https://www.diariopaillaco.cl/',
        'https://www.lapaila.cl/',
        'https://www.suractual.cl/',
        # los Lagos
        'https://www.diariodepuertomontt.cl/',
        'https://www.diariochiloe.cl/',
        'https://www.diariodeosorno.cl/',
        'https://elhuemul.cl/',
        'http://diariopuertovaras.cl/',
        'https://www.eha.cl/',
        # Aysén
        'https://www.diarioregionalaysen.cl/',
        'http://www.eldivisadero.cl/',
        'https://www.elchelenko.cl/',
        'http://web.elpatagondomingo.cl/',
        # Magallanes
        'https://laprensaaustral.cl/',
        'https://www.elpinguino.com/',
        'https://elmagallanico.com/',
        # Innovación
        'https://innovacion.cl/',
        'https://innovacionchilena.cl/',
        'https://portalinnova.cl/noticias-de-innovacion/',
        # Deportes
        'https://www.alairelibre.cl/',
        'https://www.encancha.cl/',
        'https://chile.as.com/',
        'https://m.alairelibre.cl/',
        # Ciencia
        'https://www.cienciaenchile.cl/category/noticias/'
    ],
    'argentina': [
        # BA
        'http://www.24baires.com/',
        'https://www.ambito.com/',
        'https://www.ahoramardelplata.com.ar/',
        'https://www.baenegocios.com/',
        'https://www.clarin.com/',
        'https://www.cronista.com/',
        'http://www.dehoy.com.ar/',
        'https://www.diarioelatlantico.com.ar/',
        'https://www.diariolaverdad.com.ar/',
        'https://www.diariopopular.com.ar/',
        'http://www.diarioel9dejulio.com.ar/',
        'https://www.eldestapeweb.com/',
        'https://www.eldiarioar.com/',
        'http://www.elfuertediario.com.ar/',
        'https://www.pagina12.com.ar/',
        'https://www.elbonaerense.news/',
        'https://www.eleconomista.com.ar/',
        'https://www.elintransigente.com/',
        'http://www.elorden.com/',
        'http://www.haceinstantes.com/',
        'http://www.laciudadavellaneda.com.ar/',
        'https://www.laimposible.org.ar/',
        'https://www.letrap.com.ar/',
        'https://www.lanacion.com.ar/',
        'http://www.laprensa.com.ar/',
        'https://www.lapostadelnoroeste.com.ar/',
        'http://www.lavozdelpueblo.com.ar/',
        'https://www.iprofesional.com/',
        'https://www.infobae.com/',
        'https://www.noticiasargentinas.com/',
        'https://www.perfil.com/',
        'https://www.minutouno.com/',
        'https://www.cronica.com.ar/',
        'https://www.telam.com.ar/',
        'https://www.tiempoar.com.ar/',
        'http://www.varelaaldia.com.ar/',
        'https://www.viapais.com.ar/'
        # Córdoba
        'https://www.lavoz.com.ar/',
        'https://www.hoydia.com.ar/',
        'http://www.diarioalfil.com.ar/',
        # Mendoza
        'https://www.losandes.com.ar/',
        'http://www.elsol.com.ar/',
        'https://www.diariouno.com.ar/',
        'https://www.voxpopuli.net.ar/',
        'http://www.ciudadanodiario.com.ar/',
        # Misiones
        'https://www.lavozdemisiones.com/',
        'https://www.meridiano55.com/',
        'https://www.misionescuatro.com/',
        'https://www.nortemisionero.com.ar/',
        'http://www.noticiaslaregion.com.ar/',
        'https://www.oberaesnoticia.com.ar/',
        'https://www.yamisiones.com/',
        # Neuquém
        'https://www.lmneuquen.com/',
        'https://www.minutoneuquen.com/',
        'https://www.hechosdezapala.com.ar/',
        'https://sanmartinadiario.com.ar/home/',
        'https://realidadsm.com/',
        'https://www.rincon.com.ar/',
        'https://noticiasdeplottier.com.ar/',
        'https://www.limaynoticias.com.ar/',
        'https://www.diarioneuquen.com.ar/',
        'https://www.eldigitalneuquen.com.ar/',
        'https://www.mejorinformado.com/',
        'https://www.noticiasnqn.com.ar/',
        # Río Negro
        'https://www.elcordillerano.com.ar/',
        'https://www.anbariloche.com.ar/',
        'https://barilochedigital.com/',
        'https://www.barilocheopina.com/',
        'https://www.barinoticias.com.ar/',
        'https://www.vdmnoticias.com/',
        'http://www.diarioaldia.com.ar/',
        'https://www.loprincipal.com.ar/',
        'https://www.noticiasrionegro.com.ar/',
        'https://www.diariolapalabra.com.ar/',
        'https://www.rionegro.com.ar/',
        'https://lavozdecipolletti.com/',
        'https://www.noticiasnet.com.ar/',
        'https://www.bariloche2000.com/',
        # Tierra del Fuego
        'http://www.tiempofueguino.com/',
        'https://www.surenio.com.ar/',
        'http://www.p23.com.ar/',
        'https://ushuaia24.com.ar/',
        'https://www.eldiariodelfindelmundo.com/',
        'https://shelknamsur.com/',
        'https://www.notitdf.com/',
        'https://dellagonoticias.com/',
        'https://laterceraciudad.com.ar/',
        'https://www.eldiariodelfindelmundo.com/'
    ],
    'bolivia': [
        # La Paz
        'https://www.la-razon.com/',
        'https://www.bolivia.com/',
        'https://www.eldiario.net/portal/',
        'https://www.paginasiete.bo/',
        'https://www.oxigeno.bo/',
        'https://www.la-epoca.com.bo/',
        'https://ahoraelpueblo.bo/',
        'http://www.elalteno.com.bo/',
        'https://www.eabolivia.com/',
        'https://www.laventanabolivia.com/',
        # Potosí
        'https://elpotosi.net/',
        # Santa Cruz
        'https://eju.tv/',
        'https://www.eldia.com.bo/',
        'https://elmundo.com.bo/',
        'https://www.leo.bo/',
        'http://www.ver.bo/',
        'https://www.hoybolivia.com/',
        'https://diariozonanorte.com/',
        'https://monteronoticias.com/',
        'https://eldeber.com.bo/'
    ],
    'colombia': [
        # Bogotá
        'https://www.eltiempo.com/',
        'https://www.semana.com/',
        'https://www.pulzo.com/',
        'https://www.las2orillas.co/',
        'https://cambiocolombia.com/',
        'https://www.elnuevosiglo.com.co/',
        'https://extra.com.co/',
        'https://www.diarioadn.co/',
        'https://www.desdeabajo.info/',
        'https://latitud435.com/',
        'https://www.portafolio.co/',
        'https://www.bluradio.com/',
        # Bolivar
        'https://www.eluniversal.com.co/',
        'https://mundonoticias.com.co/',
        'https://bolivarense.com/',
        'https://maganguehoy.co/',
        # Chocó
        'https://elmanduco.com.co/',
        # Santander
        'https://www.vanguardia.com/',
        'https://elfrente.com.co/',
        # Sucre
        'https://sucrenoticias.com/',
        # Tolima
        'https://www.elnuevodia.com.co/nuevodia/',
        'https://www.elolfato.com/',
        'https://www.alaluzpublica.com/',
        # Valle de Cauca
        'https://www.elpais.com.co/',
        'https://www.qhubocali.com/',
        'https://occidente.co/',
        'https://www.soydebuenaventura.com/'
    ],
    'costa_rica': [
        'https://elmundo.cr/',
        'https://ncrnoticias.com/',
        'https://elguardian.cr/',
        'https://amprensa.com/',
        'https://www.observador.cr/',
        'https://www.elpais.cr/',
        'https://adiariocr.com/',
        'https://eljornalcr.com/',
        'https://pzactual.com/',
        'https://www.diarioextra.com/Home',
        'https://www.larepublica.net/',
        'https://www.lateja.cr/',
        'https://www.crhoy.com/',
        'http://www.periodicolasegundacr.com/',
        'https://www.sancarlosdigital.com/',
        'https://elsoldeoccidente.com/',
        'http://www.periodicomitierra.com/',
        'https://www.cartagohoy.com/',
        'https://www.limonhoy.com/',
        'https://www.elindependiente.co.cr/',
        'https://www.puntarenasseoye.com/'
    ],
        'ecuador': [
        # quito
        'https://www.primicias.ec/',
        'https://www.metroecuador.com.ec/',
        'https://gk.city/',
        'https://www.lahora.com.ec/',
        'https://www.ultimasnoticias.ec/',
        'https://ecuadornoticias.com/',
        # Chimborado
        'http://www.laprensa.com.ec/',
        'https://www.diariolosandes.com.ec/',
        # Esmeraldas
        'http://esmeraldasnews.com/',
        # Guayas
        'https://www.eluniverso.com/',
        'https://www.vistazo.com/',
        'https://www.expreso.ec/',
        'https://www.extra.ec/',
        'https://www.eltelegrafo.com.ec/',
        'https://quenoticias.com/',
        'https://www.larepublica.ec/',
    ],
    'espana': [
        # Madrid
        'https://www.elpais.com/',
        'https://www.elmundo.es/',
        'https://www.elconfidencial.com/',
        'https://www.elespanol.com/',
        'https://www.20minutos.es/',
        'https://www.abc.es/',
        'https://www.eldiario.es/',
        'https://www.huffingtonpost.es/',
        'https://okdiario.com/',
        'https://www.larazon.es/',
        'https://www.libertaddigital.com/',
        'https://www.europapress.es/',
        'https://www.periodistadigital.com/',
        'https://www.vozpopuli.com/',
        'https://www.eldebate.com/',
        'https://www.niusdiario.es/',
        'https://www.epe.es/es/',
        'https://www.elindependiente.com/',
        'https://www.elplural.com/',
        'https://www.infolibre.es/',
        # Castilla La Mancha
        'https://www.latribunadetoledo.es/',
        'https://www.clm24.es/',
        'https://www.encastillalamancha.es/',
        'https://elfocodetoledo.com/',
        'https://www.latribunadetalavera.es/',
        'https://lavozdetalavera.com/',
        'https://www.lavozdeltajo.com/',
        'https://www.lacerca.com/',
        'https://albapress.es/',
        'https://www.liberaldecastilla.com/',
        'https://www.enciendecuenca.com/',
        'https://www.vocesdecuenca.com/',
        'https://elfarodehellin.com/',
        # Ciencia
        'https://novaciencia.es/'
    ],
    'guatemala': [
        'https://www.soy502.com/',
        'https://lahora.gt/',
        'https://www.guatemala.com/',
        'https://www.publinews.gt/gt/',
        'https://republica.gt/',
        'https://www.ojoconmipisto.com/',
        'https://elsiglo.com.gt/',
        'https://www.prensalibre.com/',
        'https://guatefutbol.com/',
        'https://aldia.com.gt/',
        'https://elmetropolitano.com.gt/es/',
        'https://periodicoelescuintleco.com/',
        'https://lavozdexela.com/',
        'https://diariodelosaltos.com/',
        'https://nomada.gt/'
    ],
    'mexico': [
        # CDMX
        'https://www.eluniversal.com.mx/',
        'https://www.milenio.com/',
        'https://www.jornada.com.mx/',
        'https://heraldodemexico.com.mx/',
        'https://www.proceso.com.mx/',
        'https://www.sdpnoticias.com/',
        'https://lasillarota.com/',
        'https://www.reforma.com/',
        'https://www.animalpolitico.com/',
        'https://www.sinembargo.mx/',
        'https://www.elsoldemexico.com.mx/',
        'http://www.razon.com.mx/',
        'https://www.24-horas.mx/',
        'https://www.cronica.com.mx/',
        'https://www.capitalmexico.com.mx/',
        'https://www.pasala.com.mx/',
        'https://noticiasenlamira.com/',
        'https://www.ejecentral.com.mx/',
        'https://diariobasta.com/',
        'https://www.maspormas.com/',
        'http://unomasuno.com.mx/',
        'https://www.contrareplica.mx/',
        'https://www.elpuntocritico.com/',
        # Aguascalientes
        'https://www.heraldo.mx/',
        'https://www.hidrocalidodigital.com/',
        'https://www.elsoldelcentro.com.mx/',
        'https://www.lja.mx/',
        'http://aguasdigital.com/',
        # Chihuahua
        'https://www.elheraldodechihuahua.com.mx/',
        'https://www.omnia.com.mx/',
        'https://elpuntero.com.mx/inicio/',
        'https://juarezhoy.com.mx/',
        'https://nortedigital.mx/',
        'https://www.lavozdeldesierto.mx/',
        'https://codigotres.com/',
        'https://eldiariodedelicias.mx/',
        'http://www.puentelibre.mx/',
        # Guerrero
        'https://www.elsoldeacapulco.com.mx/',
        'https://anews.mx/',
        'https://sintesisdeguerrero.com.mx/',
        'https://www.laplazadiario.com.mx/',
        'https://notimundo.com.mx/',
        'https://diarioobjetivo.com.mx/',
        'https://www.elsoldechilpancingo.mx/',
        'https://www.lacronicavespertinodechilpancingo.com/',
        'https://ixtapayzihuatanejo.com/',
        'https://www.enfoqueinformativo.mx/',
        # Guanajuato
        'https://www.am.com.mx/',
        'https://www.elsoldeleon.com.mx/',
        'https://www.noticiasvespertinas.com.mx/',
        'https://www.elsoldeirapuato.com.mx/',
        'https://www.elsoldelbajio.com.mx/',
        'https://www.heraldoleon.mx/',
        'https://www.elsoldesalamanca.com.mx/',
        'https://elotroenfoque.mx/'
        # Puebla
        'https://www.elsoldepuebla.com.mx/',
        'https://www.diariocambio.com.mx/',
        'https://intoleranciadiario.com/',
        'https://www.lajornadadeoriente.com.mx/',
        'https://24horaspuebla.com/',
        'https://www.diariopuntual.com/',
        'https://elpopular.mx/',
        'https://sintesis.com.mx/',
        'https://heraldodepuebla.com/',
        'https://www.laopinionpuebla.com/',
        'https://mtpnoticias.com/',
        'https://pueblaroja.mx/',
        'https://retodiario.com/',
        'https://www.contraparte.mx/',
        'https://www.ambasmanos.mx/',
        'https://diariosinsecretos.com/',
        # Veracruz
        'https://www.diariodexalapa.com.mx/',
        'https://jornadaveracruz.com.mx/',
        'https://cronicadexalapa.com.mx/',
        'https://graficoaldia.mx/',
        'https://www.oyeveracruz.com.mx/',
        'https://mundoxalapa.com/',
        'https://heraldodexalapa.com.mx/',
        'https://www.alcalorpolitico.com/edicion/inicio.html',
        'https://www.eldictamen.mx/',
        'https://imagendeveracruz.mx/',
        'https://www.xeu.mx/',
        'https://diariodelistmo.com/',
        'https://www.liberal.com.mx/',
        'https://heraldodecoatzacoalcos.com.mx/'
    ],
    'nicaragua': [
        'https://www.laprensani.com/',
        'https://100noticias.com.ni/',
        'https://confidencial.digital/',
        'https://www.articulo66.com/',
        'https://nicaraguainvestiga.com/',
        'https://www.despacho505.com/',
        'https://ipnicaragua.com/',
        'https://www.diariobarricada.com/',
        'https://www.bolsadenoticias.com.ni/'
    ],
    'panama': [
        'https://www.critica.com.pa/',
        'https://www.laestrella.com.pa/',
        'https://www.panamaamerica.com.pa/',
        'http://elsiglo.com.pa/',
        'https://www.midiario.com/',
        'https://www.diaadia.com.pa/',
        'https://eldigitalpanama.com/',
        'https://lagacetadepanama.com/',
        'https://elcapitalfinanciero.com/',
        'https://destinopanama.com.pa/',
        'https://ensegundos.com.pa/'
    ],
    'peru': [
        # Ancash
        'https://www.ancashnoticias.com/',
        'https://www.huarazenlinea.com/',
        'https://www.elferrolchimbote.com/',
        # Lima
        'https://larepublica.pe/',
        'https://diariocorreo.pe/',
        'https://peru21.pe/',
        'https://larazon.pe/',
        'https://wayka.pe/',
        'https://www.lapatria.pe/',
        'https://andina.pe/agencia/',
        'https://ojo.pe/',
        'https://elpopular.pe/',
        'https://lamula.pe/',
        'https://elchino.pe/',
        'https://laprimera.pe/',
        'http://www.perushimpo.com/',
        # Arequipa
        'https://diariosinfronteras.com.pe/',
        'https://diariochaski.com.pe/',
        # Cajamarca
        'https://diariopanoramacajamarquino.com/',
        'https://larotativa.pe/',
        # Cuzco
        'https://diarioelsolcusco.pe/',
        # Ica
        'https://lalupa.pe/',
        'https://www.verdaddelpueblo.com/',
        'https://diariolaopinion.pe/'
        # Loreto
        'https://diariolaregion.com/',
        'https://diarioahora.pe/',
        # Piura
        'https://lahora.pe/',
        'https://eltiempo.pe/',
        'https://www.elregionalpiura.com.pe/',
        'https://walac.pe/',
        # San Martín
        'https://diariovoces.com.pe/',
        'https://moyobamba.com/',
        # Tumbes
        'https://diariohechicera.com/',
        # Uyacali
        'https://impetu.pe/'
    ],
    #'republica_dominicana': [
    #    'https://elnacional.com.do/',
    #    'https://hoy.com.do/',
    #    'https://www.almomento.net/',
    #    'https://www.elcaribe.com.do/',
    #    'https://eldia.com.do/',
    #    'https://noticiassin.com/',
    #    'https://elnuevodiario.com.do/',
    #    'https://www.ultimasnoticias.com.do/',
    #    'https://ciudadoriental.com/',
    #    'https://www.elperiodico.com.do/',
    #    'https://www.diariodigital.com.do/',
    #    'https://eldinero.com.do/',
    #    'https://listindiario.com/'
    #],
    'uruguay': [
        # Montevideo
        'https://www.elpais.com.uy/',
        'https://www.elobservador.com.uy/',
        'https://www.montevideo.com.uy/',
        'https://ladiaria.com.uy/',
        'https://www.subrayado.com.uy/',
        'https://www.carasycaretas.com.uy/',
        'https://www.uypress.net/home',
        'https://grupormultimedio.com/',
        'https://www.180.com.uy/',
        'https://www.sudestada.com.uy/10877/Inicio',
        'https://www.elpais.com.uy/ovacion',
        'https://laoraldeportiva.com.uy/',
        'https://www.lr21.com.uy/'
    ],
    'tecnologia': [
        'https://www.xataka.com/',
        'https://www.muycomputer.com/noticias/',
        'https://computerhoy.com/noticias',
        'https://www.genbeta.com/',
        'https://noticiasdelaciencia.com/',
        'https://www.scidev.net/america-latina/'
    ],
    'internacional': [
        'https://cnnespanol.cnn.com/',
        'https://actualidad.rt.com/',
        'https://israelnoticias.com/',
        'https://www.enlacejudio.com/category/noticias/noticias-de-israel/',
        'https://reporteasia.com/',
        'https://www.casafrica.es/es/africaesnoticia',
         'https://www.revistadefrente.cl/'
    ],
    'religion': [
        'https://adventist.news/es/news',
        'https://www.bibliatodo.com/NoticiasCristianas/',
        'https://www1.cbn.com/mundocristiano',
        'https://www.noticiacristiana.com/',
        'https://protestantedigital.com/',
        'https://noticias.adventistas.org/es/',
        'https://www.puertasabiertas.org/es-ES/actualidad/todos/?tagtype=Noticias',
        'https://www.acontecercristiano.net/',
        'https://www.evangelicodigital.com/',
        'https://www.religionenlibertad.com/',
        'https://www.vaticannews.va/es.html',
    ],
    'video_juegos': [
        'https://www.3djuegos.com/noticias',
        'https://www.levelup.com/noticias',
        'https://as.com/meristation/noticias/',
        'https://www.gamereactor.es/noticias/'
    ]
}